services:
  db:
    image: postgres:15-alpine
    container_name: aq_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - bma_data:/var/lib/postgresql/data
volumes:
  bma_data:
